import streamlit as st
from langchain_openai import ChatOpenAI
from langchain_core.pydantic_v1 import BaseModel, Field
from typing import List
from langchain_core.prompts import ChatPromptTemplate


class ImagePromptModel(BaseModel):
    """This is the model for the image prompt response. It contains the output of the image prompts"""

    output: List[str] = Field(
        ...,
        description="List of image prompts generated by the AI model. It should be used as a guide for creating the visual content. Output is an array of prompts.",
    )


@st.cache_data
def create_prompt_from_paragraph(paragraph: str, prompt_count: int = 4):
    llm = ChatOpenAI(
        model="gpt-3.5-turbo",
        temperature=0,
        max_tokens=None,
        timeout=None,
        max_retries=2,
    )
    messages = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                "You prompt engineer which will writing, refining and optimizing the prompts to use in image generation. Always response with array of prompts.",
            ),
            (
                "human",
                "Let's play a game, you will be my image prompt generator for a video I'm making. I'll paste here one paragraph at a time from my script, and you will give me the visuals for it. Precisely, you will give me {prompt_count} prompts for the paragraph, which will fit the storyline and create visuals that blend together. The overall mood of the video should have an profesional and futuristik, it should have a psychology-related feel throughout the video.\n\nExample prompt 1: \n A contemplative figure sits amidst a swirl of thought bubbles, each encapsulating a different expectation. Their face is a mix of curiosity and introspection, hinting at the complexities within. This image, perhaps a striking painting, captures the essence of human emotion and decision-making. The intricate details of the bubbles, each representing a unique possibility, are rendered with exquisite precision. The overall composition evokes a sense of depth and contemplation, drawing the viewer in to ponder the intricacies of the human psyche.\n\nExample prompt 2: \nA mesmerizing mirror, each reflection a distinct interpretation of one's self shaped by expectations and perceptions. The mirror's frame is elegantly carved with intricate designs, adding a touch of sophistication to the piece. Various versions of the same person morph across its surface, influenced by societal norms and personal beliefs. This captivating image, a digital illustration, showcases the intricate complexities of self-image and the power of external influences on our perception of identity. The high resolution and vibrant colors bring each reflection to life, inviting viewers to ponder the ever-changing nature of self-perception.",
            ),
            (
                "assistant",
                "Sure, I'd love to help you with that! Please go ahead and paste the paragraph of your script. I'll generate {prompt_count} image prompts for you to use as a guide for creating the visual content. Let's get started!",
            ),
            (
                "human",
                "{paragraph}",
            ),
        ]
    )

    runnable = messages | llm.with_structured_output(schema=ImagePromptModel)

    ai_msg = runnable.invoke({"paragraph": paragraph, "prompt_count": prompt_count})
    print(ai_msg)
    return ai_msg
